version: '3.1'

networks:
  back-u-network:
    external:
      name: back-u-network

services:
  web-api:
    container_name: "back-u-web-api"
    image: nginx
    volumes:
      - "./docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.template"
      - "./app:/var/www/html"
    ports:
      - "9884:80"
    environment:
      - NGINX_HOST=${NGINX_HOST_API}
    command: /bin/bash -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php-api
    networks:
      - back-u-network
  php-api:
    image: yiisoftware/yii2-php:7.3-fpm
    container_name: ${PHP_HOST}
    restart: always
    volumes:
      - "./app:/var/www/html"
      - "./.env:/var/www/html/.env"
    networks:
      - back-u-network
  mysql-api:
    image: mysql:5.7.27
    container_name: ${MYSQL_HOST}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./docker/data/db/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - back-u-network